language: node_js
os:
  - "linux"

node_js:
  - "8"

before_install:
  - cd app

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  target_branch: gh-pages
  local_dir: app/dist
  on:
    branch: master
